default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: development_opengymsf_admin

test:
  <<: *default
  database: test_opengymsf_admin

production:
  <<: *default
  database: production_opengymsf_admin
